### ISSUE TITLE
Remove source_instance tag

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry-incubator/go-loggregator#17]
This is redundant and not needed:

https://github.com/cloudfoundry-incubator/go-loggregator/blob/17682e3bc1157ea3b83e292ef6ee974ba992918c/ingress_client.go#L161-L163
https://github.com/cloudfoundry-incubator/go-loggregator/blob/17682e3bc1157ea3b83e292ef6ee974ba992918c/ingress_client_test.go#L85-L106

SourceId on the envelope is where this is stored.

**Comment by enocom** [comment]
Completed in 6ba5e78b48c09d2aca1914069baca98accbaa607.
